module.exports = {
  Produce: 0,
  Fetch: 1,
  ListOffsets: 2,
  Metadata: 3,
  LeaderAndIsr: 4,
  StopReplica: 5,
  UpdateMetadata: 6,
  ControlledShutdown: 7,
  OffsetCommit: 8,
  OffsetFetch: 9,
  GroupCoordinator: 10,
  JoinGroup: 11,
  Heartbeat: 12,
  LeaveGroup: 13,
  SyncGroup: 14,
  DescribeGroups: 15,
  ListGroups: 16,
  SaslHandshake: 17,
  ApiVersions: 18, // ApiVersions v0 on Kafka 0.10
  CreateTopics: 19,
  DeleteTopics: 20,
  DeleteRecords: 21,
  InitProducerId: 22,
  OffsetForLeaderEpoch: 23,
  AddPartitionsToTxn: 24,
  AddOffsetsToTxn: 25,
  EndTxn: 26,
  WriteTxnMarkers: 27,
  TxnOffsetCommit: 28,
  DescribeAcls: 29,
  CreateAcls: 30,
  DeleteAcls: 31,
  DescribeConfigs: 32,
  AlterConfigs: 33, // ApiVersions v0 and v1 on Kafka 0.11
  AlterReplicaLogDirs: 34,
  DescribeLogDirs: 35,
  SaslAuthenticate: 36,
  CreatePartitions: 37,
  CreateDelegationToken: 38,
  RenewDelegationToken: 39,
  ExpireDelegationToken: 40,
  DescribeDelegationToken: 41,
  DeleteGroups: 42, // ApiVersions v2 on Kafka 1.0
  ElectPreferredLeaders: 43,
  ElectLeaders: 43, // Alias: renamed from ElectPreferredLeaders in Kafka 2.4
  IncrementalAlterConfigs: 44,
  AlterPartitionReassignments: 45,
  ListPartitionReassignments: 46,
  // Kafka 3.0+ API keys
  OffsetDelete: 47,
  DescribeClientQuotas: 48,
  AlterClientQuotas: 49,
  DescribeUserScramCredentials: 50,
  AlterUserScramCredentials: 51,
  Vote: 52,
  BeginQuorumEpoch: 53,
  EndQuorumEpoch: 54,
  DescribeQuorum: 55,
  AlterPartition: 56,
  UpdateFeatures: 57,
  Envelope: 58,
  FetchSnapshot: 59,
  DescribeCluster: 60,
  DescribeProducers: 61,
  BrokerRegistration: 62,
  BrokerHeartbeat: 63,
  UnregisterBroker: 64,
  DescribeTransactions: 65,
  ListTransactions: 66,
  AllocateProducerIds: 67,
  // Kafka 3.3+ KRaft API keys
  ConsumerGroupHeartbeat: 68,
  ConsumerGroupDescribe: 69,
  ControllerRegistration: 70,
  GetTelemetrySubscriptions: 71,
  PushTelemetry: 72,
  AssignReplicasToDirs: 73,
  ListClientMetricsResources: 74,
  DescribeTopicPartitions: 75,
  // Kafka 4.0+ Share Group API keys (KIP-932)
  ShareGroupHeartbeat: 76,
  ShareGroupDescribe: 77,
  ShareFetch: 78,
  ShareAcknowledge: 79,
  // Kafka 4.1+ API keys
  AddRaftVoter: 80,
  RemoveRaftVoter: 81,
  // Kafka 4.2+ API keys
  UpdateRaftVoter: 82,
  ReadShareGroupStateSummary: 83,
}
